version: "3"
services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
